// Generated by CoffeeScript 1.3.3
(function() {
  var basePathMeta, baseReadAttr, baseSelectAttr, pathDeveloper, pathRating;

  basePathMeta = '.doc-metadata-list';

  baseSelectAttr = 'itemprop';

  baseReadAttr = 'content';

  pathDeveloper = "" + basePathMeta + " *[itemprop=\"author\"]";

  pathRating = "" + basePathMeta + " *[itemprop=\"aggregateRating\"]";

  exports.paths = {
    "app_name": {
      "selector": "" + basePathMeta + " *[" + baseSelectAttr + "=\"name\"]",
      "type": "" + baseReadAttr
    },
    "logo": {
      "selector": "" + basePathMeta + " *[" + baseSelectAttr + "=\"image\"]",
      "type": "" + baseReadAttr
    },
    "developer": {
      "selector": "" + pathDeveloper + " *[" + baseSelectAttr + "=\"name\"]",
      "type": "" + baseReadAttr
    },
    "developer_link": {
      "selector": "" + pathDeveloper + " *[" + baseSelectAttr + "=\"url\"]",
      "type": "" + baseReadAttr
    },
    "rating": {
      "selector": "" + pathRating + " *[" + baseSelectAttr + "=\"ratingValue\"]",
      "type": "" + baseReadAttr
    },
    "ratingCount": {
      "selector": "" + pathRating + " *[" + baseSelectAttr + "=\"ratingCount\"]",
      "type": "" + baseReadAttr
    },
    "last_update": {
      "selector": "" + basePathMeta + " *[" + baseSelectAttr + "=\"datePublished\"]",
      "type": "text"
    },
    "version": {
      "selector": "" + basePathMeta + " *[" + baseSelectAttr + "=\"softwareVersion\"]",
      "type": "text"
    },
    "os_version": {
      "selector": "" + basePathMeta + " *[" + baseSelectAttr + "=\"operatingSystems\"] + dd",
      "type": "text"
    },
    "categorie": {
      "selector": "" + basePathMeta + " a[href$=\"category-nav\"]",
      "type": "href"
    },
    "downloads": {
      "selector": "" + basePathMeta + " *[" + baseSelectAttr + "=\"numDownloads\"]",
      "type": "text"
    },
    "fileSize": {
      "selector": "" + basePathMeta + " *[" + baseSelectAttr + "=\"fileSize\"]",
      "type": "text"
    },
    "price": {
      "selector": "" + basePathMeta + " *[" + baseSelectAttr + "=\"price\"]",
      "type": "" + baseReadAttr
    },
    "description": {
      "selector": ".doc-overview *[" + baseSelectAttr + "=\"description\"]",
      "type": "text"
    },
    "screenshots": {
      "selector": ".doc-overview-screenshots .doc-screenshot-section img",
      "type": "src"
    },
    "banner": {
      "selector": ".doc-banner-image-container img",
      "type": "src"
    },
    "app_url": {
      "selector": ".page-content > *[" + baseSelectAttr + "=\"url\"]",
      "type": "" + baseReadAttr
    }
  };

}).call(this);
